# Generated by Django 4.2.6 on 2023-11-30 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("sets", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=60)),
                ("destination", models.CharField(max_length=60)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="travel.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_destination", models.CharField(max_length=60)),
                ("time_destination", models.TimeField()),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="travel.travel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_board", models.CharField(max_length=60)),
                ("time_board", models.TimeField()),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="travel.travel",
                    ),
                ),
            ],
        ),
    ]
